# Generated by Django 3.2.4 on 2021-07-10 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='job_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True)),
                ('special', models.CharField(blank=True, max_length=255, null=True)),
                ('date_posted', models.DateTimeField()),
                ('url', models.CharField(max_length=255)),
                ('website', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'job_data',
            },
        ),
        migrations.CreateModel(
            name='user_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('special', models.CharField(max_length=255)),
                ('ip_address', models.CharField(max_length=255)),
                ('user_agent', models.CharField(max_length=255)),
                ('exp_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'user_history',
            },
        ),
    ]
